### ISSUE TITLE
为啥还是12层

### ISSUE THREAD

**Issue by YC-wind** [policeme/roberta-wwm-base-distill#1]
百度云地址config
{
  "attention_probs_dropout_prob": 0.1, 
  "directionality": "bidi", 
  "hidden_act": "gelu", 
  "hidden_dropout_prob": 0.1, 
  "hidden_size": 768, 
  "initializer_range": 0.02, 
  "intermediate_size": 3072, 
  "max_position_embeddings": 512, 
  "num_attention_heads": 12, 
  "num_hidden_layers": 12, 
  "pooler_fc_size": 768, 
  "pooler_num_attention_heads": 12, 
  "pooler_num_fc_layers": 3, 
  "pooler_size_per_head": 128, 
  "pooler_type": "first_token_transform", 
  "type_vocab_size": 2, 
  "vocab_size": 21128
}

为啥还是 12层，模型并没有减少耶，按理说参数量会减少

**Comment by xiongma** [comment]
这个是在roberta base版本的基础上蒸馏的 没有改变模型结构 看下README吧

**Comment by yaleimeng** [comment]
@policeme  既然没有改变模型结构，那蒸馏主要带来什么好处呢？是1个点的成绩提高吗？
工业界主要期待的是更小的体积，更快的预测速度。这个似乎跟参数量是正相关的。

**Comment by xiongma** [comment]
这个只是base的初步蒸馏模型 为了证明方法可行性  更小体积模型在训练中，预计1.20号左右出来
