### ISSUE TITLE
您好，我想问一个关于教师数据生成的问题

### ISSUE THREAD

**Issue by LLLLLLoki** [policeme/roberta-wwm-base-distill#2]
您在将老师模型生成的数据保存成tf_record的格式，这样会比原数据大很多，有没有什么方法，生成一个batch 的数据喂给学生模型训练，这种边生成边训练的方法，我之前试过，但是代码没写成功

**Comment by xiongma** [comment]
这种我也试过，没有成功，最后还是采用了repo上的方法


from Alimail iPhone
 ------------------Original Mail ------------------
